services:
  - type: web
    name: safecall-cm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn safecall.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False