# SafeCall CM - Deploiement v2
services:
  - type: web
    name: safecall-cm
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput && python create_admin.py
    startCommand: gunicorn safecall.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0