# Generated by Django 5.2.15 on 2026-07-07 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienMalveillant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('domaine', models.CharField(max_length=200)),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt MTN/Orange'), ('appel_frauduleux', 'Appel frauduleux'), ('lien_suspect', 'Lien suspect'), ('faux_bank', 'Faux message bancaire'), ('whatsapp', 'Arnaque WhatsApp'), ('autre', 'Autre')], max_length=50)),
                ('nombre_signalements', models.IntegerField(default=1)),
                ('niveau', models.IntegerField(choices=[(1, 'Suspect'), (2, 'Très suspect'), (3, 'Confirmé')], default=1)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lien Malveillant',
                'verbose_name_plural': 'Liens Malveillants',
            },
        ),
        migrations.CreateModel(
            name='NumeroCommunautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt MTN/Orange'), ('appel_frauduleux', 'Appel frauduleux'), ('lien_suspect', 'Lien suspect'), ('faux_bank', 'Faux message bancaire'), ('whatsapp', 'Arnaque WhatsApp'), ('autre', 'Autre')], max_length=50)),
                ('niveau', models.IntegerField(choices=[(1, 'Suspect'), (2, 'Très suspect'), (3, 'Confirmé')], default=1)),
                ('nombre_signalements', models.IntegerField(default=1)),
                ('score_confiance', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('premier_signalement', models.DateTimeField(auto_now_add=True)),
                ('dernier_signalement', models.DateTimeField(auto_now=True)),
                ('confirme', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Numéro Frauduleux',
                'verbose_name_plural': 'Numéros Frauduleux',
            },
        ),
        migrations.CreateModel(
            name='CampagneArnaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt MTN/Orange'), ('appel_frauduleux', 'Appel frauduleux'), ('lien_suspect', 'Lien suspect'), ('faux_bank', 'Faux message bancaire'), ('whatsapp', 'Arnaque WhatsApp'), ('autre', 'Autre')], max_length=50)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('nombre_signalements', models.IntegerField(default=0)),
                ('numeros', models.ManyToManyField(blank=True, to='api.numerocommunautaire')),
            ],
            options={
                'verbose_name': "Campagne d'Arnaque",
                'verbose_name_plural': "Campagnes d'Arnaque",
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telephone', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('protection_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_signale', models.CharField(max_length=20)),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt MTN/Orange'), ('appel_frauduleux', 'Appel frauduleux'), ('lien_suspect', 'Lien suspect'), ('faux_bank', 'Faux message bancaire'), ('whatsapp', 'Arnaque WhatsApp'), ('autre', 'Autre')], max_length=50)),
                ('message_recu', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Signalement',
            },
        ),
        migrations.CreateModel(
            name='BlocageUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.CharField(max_length=20)),
                ('date_blocage', models.DateTimeField(auto_now_add=True)),
                ('bloque_manuellement', models.BooleanField(default=False)),
                ('exception', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Blocage',
                'unique_together': {('utilisateur', 'numero_bloque')},
            },
        ),
    ]
