# Generated by Django 5.2.15 on 2026-07-11 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienMalveillant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('domaine', models.CharField(max_length=200)),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt Mobile Money'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50)),
                ('nombre_signalements', models.IntegerField(default=1)),
                ('niveau', models.IntegerField(choices=[(1, 'Suspect'), (2, 'Très suspect'), (3, 'Confirmé')], default=1)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lien Malveillant',
                'verbose_name_plural': 'Liens Malveillants',
            },
        ),
        migrations.CreateModel(
            name='NumeroCommunautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('operateur', models.CharField(choices=[('mtn', 'MTN Cameroun'), ('orange', 'Orange Cameroun'), ('camtel', 'Camtel'), ('banque', 'Banque'), ('autre', 'Autre / Inconnu')], max_length=20)),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt Mobile Money'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50)),
                ('niveau', models.IntegerField(choices=[(1, 'Suspect'), (2, 'Très suspect'), (3, 'Confirmé')], default=1)),
                ('nombre_signalements', models.IntegerField(default=0)),
                ('score_confiance', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('premier_signalement', models.DateTimeField(auto_now_add=True)),
                ('dernier_signalement', models.DateTimeField(auto_now=True)),
                ('confirme', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Numéro Frauduleux',
                'verbose_name_plural': 'Numéros Frauduleux',
                'ordering': ['-nombre_signalements'],
            },
        ),
        migrations.CreateModel(
            name='TypeImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Type d'impact",
                'verbose_name_plural': "Types d'impact",
            },
        ),
        migrations.CreateModel(
            name='CampagneArnaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt Mobile Money'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('nombre_signalements', models.IntegerField(default=0)),
                ('numeros', models.ManyToManyField(blank=True, to='api.numerocommunautaire')),
            ],
            options={
                'verbose_name': "Campagne d'Arnaque",
                'verbose_name_plural': "Campagnes d'Arnaque",
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telephone', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('protection_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='BlocageUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.CharField(max_length=20)),
                ('date_blocage', models.DateTimeField(auto_now_add=True)),
                ('bloque_manuellement', models.BooleanField(default=False)),
                ('exception', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Blocage',
                'unique_together': {('utilisateur', 'numero_bloque')},
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_declarant', models.CharField(blank=True, max_length=100)),
                ('numero_declarant', models.CharField(blank=True, max_length=20)),
                ('afficher_identite', models.BooleanField(default=False)),
                ('numero_signale', models.CharField(max_length=20)),
                ('operateur', models.CharField(choices=[('mtn', 'MTN Cameroun'), ('orange', 'Orange Cameroun'), ('camtel', 'Camtel'), ('banque', 'Banque'), ('autre', 'Autre / Inconnu')], max_length=20)),
                ('nom_precis', models.CharField(blank=True, max_length=100)),
                ('type_arnaque', models.CharField(choices=[('faux_depot', 'Faux dépôt Mobile Money'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50)),
                ('moyen_utilise', models.CharField(choices=[('sms', 'SMS'), ('appel', 'Appel téléphonique'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('autre', 'Autre')], max_length=20)),
                ('date_incident', models.DateField()),
                ('heure_incident', models.TimeField(blank=True, null=True)),
                ('date_approximative', models.BooleanField(default=False)),
                ('ville_incident', models.CharField(blank=True, max_length=100)),
                ('region_incident', models.CharField(blank=True, max_length=100)),
                ('attaque_reussie', models.BooleanField(default=False)),
                ('montant_perdu', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('description_impact', models.TextField(blank=True)),
                ('message_recu', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.profilutilisateur')),
                ('types_impact', models.ManyToManyField(blank=True, related_name='signalements', to='api.typeimpact')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
                'unique_together': {('utilisateur', 'numero_signale')},
            },
        ),
    ]
