# Generated by Django 5.2.15 on 2026-07-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerocommunautaire',
            name='nom_precis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campagnearnaque',
            name='type_arnaque',
            field=models.CharField(choices=[('faux_depot', 'Faux dépôt'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lienmalveillant',
            name='type_arnaque',
            field=models.CharField(choices=[('faux_depot', 'Faux dépôt'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='numerocommunautaire',
            name='type_arnaque',
            field=models.CharField(choices=[('faux_depot', 'Faux dépôt'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='type_arnaque',
            field=models.CharField(choices=[('faux_depot', 'Faux dépôt'), ('faux_conseiller', 'Faux conseiller / agent'), ('lien_suspect', 'Lien suspect'), ('fausse_loterie', 'Fausse loterie / faux gain'), ('faux_bancaire', 'Faux message bancaire'), ('appel_frauduleux', 'Appel frauduleux (numéro déjà signalé)'), ('autre', 'Autre')], max_length=50),
        ),
    ]
